# Generated by Django 4.1.7 on 2023-04-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='username',
            field=models.CharField(default='default_username', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='username',
            field=models.CharField(default='default_username', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
