# Generated by Django 4.1.7 on 2023-04-29 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_company_username_recruiter_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='username',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='username',
        ),
    ]
