# Generated by Django 4.1.7 on 2023-04-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_company_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
