# Generated by Django 4.1.7 on 2023-05-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_resume_selected_for_job_shortlisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
