# Generated by Django 4.1.7 on 2023-05-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_resume_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlisted',
            name='resume_score',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=7),
        ),
    ]
