# Generated by Django 4.2.1 on 2023-05-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_job_number_of_openings'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlisted',
            name='contact_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
