# Generated by Django 4.2.1 on 2023-05-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_shortlisted_resume_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortlisted',
            name='contact_details',
        ),
        migrations.AddField(
            model_name='shortlisted',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shortlisted',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
