# Generated by Django 4.2.1 on 2023-05-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_remove_shortlisted_contact_details_shortlisted_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlisted',
            name='email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
