# Generated by Django 4.2.1 on 2023-05-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_shortlisted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlisted',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shortlisted',
            name='Interview_Person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shortlisted',
            name='Status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shortlisted',
            name='Time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
