# Generated by Django 4.2.1 on 2023-05-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_shortlisted_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlisted',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shortlisted',
            name='Status',
            field=models.CharField(blank=True, default='Pending', max_length=100, null=True),
        ),
    ]
